home/urls.py
from django.urls import path
from .views import index, keuangan, surat, publikasi

app_name = 'home'

urlpatterns = [
    path('', index, name='home'),
    path('keuangan', keuangan, name='keuangan'),
    path('surat', surat, name='surat'),
    path('publikasi', publikasi, name='publikasi'),
]

publikasi/urls.py
from . import views
from django.urls import path

app_name = 'publikasi'

urlpatterns = [
    path('form', views.formPublikasi, name='formpublikasi'),
    path('postformpublikasi', views.postFormPublikasi, name='postformpublikasi'),
    path('detail/<str:id>', views.detail, name='detail'),
    path('delete', views.delete, name='delete')
]

reimbursement/urls.py
from django.urls import path
from .views import *

app_name = 'reimbursement'

urlpatterns = [
    path('form', form_reimbursement, name='form_reimbursement'),
    path('postForm', post_form_reimbursement, name='post_form_reimbursement'),
    path('detail/<str:id>', detail, name='detail'),
    path('delete', delete, name='delete')
]

requestmanagementsystem/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('surat/', include(('surat.urls', 'surat'), namespace='surat')),
    path('keuangan/', include(('reimbursement.urls', 'reimbursement'), namespace='reimbursement')),
    path('upload-photo', include('backend.urls')),
    path('publikasi/', include(('publikasi.urls', 'publikasi'), namespace='publikasi')),
    path('dashboard-pengurus/', include(('dashpengurus.urls', 'dashpengurus'), namespace='dashboard_pengurus')),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('feedback/', include(('feedback.urls', 'feedback'), namespace='feedback')),

]

surat/urls.py
from . import views
from django.urls import path

app_name = 'surat'

urlpatterns = [
    path('form', views.formSurat, name='formsurat'),
    path('postformsurat', views.postFormSurat, name='postformsurat'),
    path('detail/<str:id>', views.detail, name='detail'),
    path('delete', views.delete, name='delete')

]

user/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    path('login', login, name='login'),
    path('postlogin', postLogin, name='postlogin'),
    path('signup', signUp, name='signup'),
    path('postsignup', postSignUp, name='postsignup'),
    path('dashboard', dashboard, name='dashboard'),
    path('logout', logout, name='logout')
]

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'home.html')

def keuangan(request):
    return render(request, 'keuangan.html')

def surat(request):
    return render(request, 'surat.html')

def publikasi(request):
    return render(request, 'publikasi.html')

publikasi/views.py
import json

from django.http import Http404
from django.shortcuts import render, redirect, HttpResponseRedirect
from backend.CRUD.crud_publikasi import publikasi_create, publikasi_read,publikasi_delete
from backend.CRUD.crud_user import user_read
from backend.misc import firebase_init, getPhoto

# Initialize Firebase Database
fauth = firebase_init


# ---------------------
# Form Request Publikasi Keluar
# --------------------
def formPublikasi(request):
    try:
        if (request.session['uid']):
            print(1)
            if (fauth.get_account_info(request.session['uid'])):
                print(2)
                return render(request, 'form_publikasi.html')
            else:
                return redirect("/user/logout")
    except:
        return redirect("/user/login")


def postFormPublikasi(request):
    judul_konten = request.POST.get("judul_konten")
    deskripsi_kegiatan = request.POST.get("deskripsi_kegiatan")
    kanal_publikasi = request.POST.get("kanal_publikasi")
    link = request.POST.get("link")
    insidental = request.POST.get("insidental")
    id_feedback = ""
    
    if (insidental == "True"):
        insidental = True
    else:
        insidental = False
        bukti = ""

    message = publikasi_create(request, judul_konten, id_feedback, deskripsi_kegiatan, kanal_publikasi, link, insidental)
    print(message)
    if message != "terjadi error":
        return redirect("/publikasi/detail/" + message)
    else:
        return redirect("user:logout")


# ---------------------
# Detail Publikasi Keluar
# --------------------
def detail(request, id):
    try:
        if (request.session['uid']):
            print(1)
            user_session = fauth.get_account_info(request.session['uid'])
            print(1)
            if (user_session):
                print(1)
                data_detail = publikasi_read(id)
                print(1)
                user = user_read(user_session['users'][0]['localId'])
                print(1)
                print(user)
                if (data_detail != []):
                    print(1)
                    print(data_detail)
                    if (user["id"] == data_detail["id_pemohon"] or "publikasi" in user["admin"]):
                        print(1)
                        # Get Dokumen Files
                        if ("publikasi" in user["admin"]):
                            admin = "true"
                        else:
                            admin = "false"
                        try:
                            url = getPhoto.getPhoto(data_detail["token_dokumen"][0])
                            dokumen = url
                        except:
                            dokumen = ""
                        return render(request, 'publikasi_details.html', {
                            'data': data_detail,
                            'user': user,
                            'admin': admin,
                            'id': id,
                            'dokumen': dokumen,
                        })
                    else:
                        raise Http404
            else:
                return redirect("/user/logout")
        else:
            return redirect("/user/login")
    except:
        return redirect("/user/login")


def delete(request):
    try:
        if (request.session['uid']):
            user_session = fauth.get_account_info(request.session['uid'])
            if (user_session):
                user = user_read(user_session['users'][0]['localId'])
                if ("publikasi" in user["admin"]):
                    print('masuk')
                    id_request = request.POST.get("id_request")
                    print(id_request)
                    data = publikasi_delete(id_request)
                    print(data)
                    return redirect('home:publikasi')
            else:
                return redirect('user:logout')
    except:
        return redirect('user:signin')

surat/views.py
import json

from django.http import Http404
from django.shortcuts import render, redirect
from backend.CRUD.crud_surat import surat_create, surat_read,surat_delete
from backend.CRUD.crud_user import user_read
from backend.constant.links import links_surat
from backend.constant.tahapan import tahap_surat_keluar
from backend.misc import firebase_init, getPhoto

# Initialize Firebase Database
fauth = firebase_init


# ---------------------
# Form Request Surat Keluar
# --------------------
def formSurat(request):
    try:
        if (request.session['uid']):
            if (fauth.get_account_info(request.session['uid'])):
                return render(request, 'form_surat.html')
            else:
                return redirect("/user/logout")
    except:
        return redirect("/user/login")

def postFormSurat(request):
    judul = request.POST.get("judul")
    nama_kegiatan = request.POST.get("nama_kegiatan")
    deskripsi = request.POST.get("deskripsi")
    jenis_surat = request.POST.get("jenis")
    link = request.POST.get("linkdocs")
    insidental = request.POST.get("insidental")

    message = surat_create(request, judul, nama_kegiatan, deskripsi, jenis_surat, link, insidental)
    print(message)
    if message != "terjadi error":
        return redirect("/surat/detail/" + message)
    else:
        return redirect("/user/logout")


# ---------------------
# Detail Surat Keluar
# --------------------
def detail(request, id):
    # try:
        print("masuk")
        if (request.session['uid']):
            print("masuk1")
            user_session = fauth.get_account_info(request.session['uid'])
            if (user_session):
                print("masuk2")
                data_detail = surat_read(id)
                user = user_read(user_session['users'][0]['localId'])
                if (data_detail != []):
                    print("masuk3")
                    if (user["id"] == data_detail["id_pemohon"] or "surat" in user["admin"]):
                        print("masuk4")
                        # Get Dokumen Files
                        if ("surat" in user["admin"]):
                            print("masuk5")
                            admin = "true"
                        else:
                            admin = "false"
                        print("mssuk6")
                        return render(request, 'surat_details.html', {
                            'data': data_detail,
                            'user': user,
                            'admin': admin,
                            'id': id,
                        })
                    else:
                        raise Http404
            else:
                return redirect("/user/logout")
        else:
            return redirect("/user/login")
    # except:
    #     return redirect("/user/login")


def delete(request):
    try:
        if (request.session['uid']):
            user_session = fauth.get_account_info(request.session['uid'])
            if (user_session):
                user = user_read(user_session['users'][0]['localId'])
                if ("surat" in user["admin"]):
                    print('masuk')
                    id_request = request.POST.get("id_request")
                    print(id_request)
                    data = surat_delete(id_request)
                    print(data)
                    return redirect('home:surat')
            else:
                return redirect('user:logout')
    except:
        return redirect('user:signin')

home/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <meta charset="UTF-8">
    <title>RMS - Request Management System</title>
<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
  <script type="application/javascript" src="{% static 'main/js/script.js' %}"></script>
{% endblock meta %}

{% block content %}
	<div class="content-home">
		<div class="home-top">
			<div class="home-top-color-filter">
				<div class="only-desktop">
					<h1>Get your task done<br>By using RMS</h1>
					<p>Permudah segala urusanmu dengan Request Management System</p>
					{% if not request.session.uid %}
					<a href="{% url 'user:login' %}" class="button fit-content">Login Now!</a>
					{% endif %}
				</div>
				<object class="only-desktop" data="{% static 'main/svg/Scrum-board-pana.svg' %}" type="image/svg+xml"></object>
				<div class="only-mobile">
					<object data="{% static 'main/svg/Scrum-board-pana.svg' %}" type="image/svg+xml"></object>
					<div class="only-mobile">
						<h1>Get your task done<br>By using RMS</h1>
						<p>Permudah segala urusanmu dengan Request Management System</p>
						{% if not request.session.uid %}
						<a href="" class="button fit-content">Login Now!</a>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
		<div class="home-middle">
			<div class="home-middle-top">
				<object data="{% static 'main/svg/Mind-map-pana.svg' %}" type="image/svg+xml"></object>
				<div>
					<h2>Apa Itu Request Management System?</h2>
					<p>Request Management System adalah webapp untuk mempercepat dan mempermudah alur permintaan yang ada di internal suatu organisasi.</p>
				</div>
			</div>
			<div class="home-middle-middle">
				<div class="only-desktop">
					<h2>Kami menawarkan kemudahan</h2>
					<p>Misi kami adalah untuk meningkatkan efisiensi, efektifitas, dan memberikan kemudahan bagi para fungsionaris organisasi dan jajaran dibawahnya dalam melakukan permintaan.</p>
					<ul>
						<li><p>Seluruh informasi terintegrasi dalam satu tempat<p></li>
						<li><p>Memudahkan tracking progress permintaan<p></li>
						<li><p>Meminimalisir miskomunikasi dalam proses alur permintaan<p></li>
					</ul>
				</div>
				<object data="{% static 'main/svg/Features-Overview-pana.svg' %}" type="image/svg+xml"></object>
				<div class="only-mobile">
					<h2>Kami menawarkan kemudahan</h2>
					<p>Misi kami adalah untuk meningkatkan efisiensi, efektifitas, dan memberikan kemudahan bagi para fungsionaris organisasi dan jajaran dibawahnya dalam melakukan permintaan.</p>
					<ul>
						<li><p>Seluruh informasi terintegrasi dalam satu tempat<p></li>
						<li><p>Memudahkan tracking progress permintaan<p></li>
						<li><p>Meminimalisir miskomunikasi dalam proses alur permintaan<p></li>
					</ul>
				</div>
			</div>
			<div>
				<h1 class="home-features">Fitur Fitur</h1>
				<div class="home-middle-bottom">
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Piggy-bank-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div class="only-desktop">
								<h2>Keuangan</h2>
								<p>Butuh melakukan permintaan reimburse?</p>
							</div>
							<div class="only-mobile">
								<h2>Keuangan</h2>
							</div>
							<a href="" class="button fit-content">Telusuri</a>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Content-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div class="only-desktop">
								<h2>Publikasi</h2>
								<p>Butuh melakukan permintaan publikasi di kanal media?</p>
							</div>
							<div class="only-mobile">
								<h2>Publikasi</h2>
							</div>
							<a href="" class="button fit-content">Telusuri</a>
						</div>
					 </div>
					<div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Mail-sent-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div class="only-desktop">
								<h2>Surat Menyurat</h2>
								<p>Ingin meminta persetujuan dan tanda tangan serta masalah persuratan?</p>
							</div>
							<div class="only-mobile">
								<h2>Surat Menyurat</h2>
							</div>
							<a href="" class="button fit-content">Telusuri</a>
						</div>
					 </div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

home/templates/keuangan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <meta charset="UTF-8">
    <title>RMS - Keuangan</title>
<link rel="stylesheet" href="{% static 'main/css/style-detail.css' %}">
  <script type="application/javascript" src="{% static 'main/js/script.js' %}"></script>
{% endblock meta %}

{% block content %}
	<div class="content-home">
        <div class="filler"></div>
        <div class="home-top">
			<div class="home-top-color-filter">
				<div>
					<h1>Keuangan</h1>
					<p>Lakukan pengajuan reimbursement, advanced, dan penyetoran kamu dengan memencet tombol di bawah ya</p>
                    <a href="{% url 'reimbursement:form_reimbursement' %}" class="button fit-content">Ajukan Reimbursement</a>
				</div>
				<object class="only-desktop" data="{% static 'main/svg/Piggy-bank-pana.svg' %}" type="image/svg+xml"></object>
			</div>
		</div>
        <div class="home-middle">
			<div class="home-middle-top">
				<object data="{% static 'main/svg/Questions-pana.svg' %}" type="image/svg+xml"></object>
				<div class="only-desktop">
					<h2>Simak cara melakukan permintaan keuanganmu di bawah ini!</h2>
					<p>Kalian masih bingung cara menggunakan website RMS? Yuk, Kami ajarin!</p>
				</div>
				<div class="only-mobile">
					<h2>Simak cara melakukan permintaan keuanganmu di bawah ini!</h2>
					<p>Kalian masih bingung cara menggunakan website RMS? Yuk, Kami ajarin!</p>
				</div>
			</div>
			<div>
				<h1 class="home-features">Langkah-langkah</h1>
				<div class="home-middle-bottom">
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Piggy-bank-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Isi Form</h2>
								<p>Isi form permintaan dengan memencet tombol di bawah ini</p>
							</div>
							<a href="" class="button fit-content">Telusuri</a>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Content-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2 id="tahap-1">Masukkan data yang dibutuhkan</h2>
								<p>Butuh melakukan permintaan publikasi di kanal media organisasi?</p>
							</div>
						</div>
					 </div>
					<div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Mail-sent-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Pantau progress permintaan</h2>
								<p>Ingin meminta persetujuan dan tanda tangan dari organisasi?</p>
							</div>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Customer-Survey-amico.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Selesai</h2>
								<p>Membutuhkan survei untuk kepentingan penelitian dan pengembangan?</p>
							</div>
						</div>
					 </div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

home/templates/publikasi.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <meta charset="UTF-8">
    <title>RMS - Keuangan</title>
<link rel="stylesheet" href="{% static 'main/css/style-detail.css' %}">
  <script type="application/javascript" src="{% static 'main/js/script.js' %}"></script>
{% endblock meta %}

{% block content %}
	<div class="content-home">
        <div class="filler"></div>
        <div class="home-top">
			<div class="home-top-color-filter">
				<div>
					<h1>Publikasi</h1>
					<p>Lakukan pengajuan permohononan publikasi kamu dengan memencet tombol di bawah ya</p>
                    <a href="{% url 'publikasi:formpublikasi' %}" class="button fit-content">Ajukan permohonan publikasi</a>
				</div>
				<object class="only-desktop" data="{% static 'main/svg/Mobile-Marketing-bro.svg' %}" type="image/svg+xml"></object>
			</div>
		</div>
        <div class="home-middle">
			<div class="home-middle-top">
				<object data="{% static 'main/svg/Questions-pana.svg' %}" type="image/svg+xml"></object>
				<div class="only-desktop">
					<h2>Simak cara melakukan permintaan keuanganmu di bawah ini!</h2>
					<p>Kalian masih bingung cara menggunakan website RMS? Yuk, Kami ajarin!</p>
				</div>
				<div class="only-mobile">
					<h2>Simak cara melakukan permintaan keuanganmu di bawah ini!</h2>
					<p>Kalian masih bingung cara menggunakan website RMS? Yuk, Kami ajarin!</p>
				</div>
			</div>
			<div>
				<h1 class="home-features">Langkah-langkah</h1>
				<div class="home-middle-bottom">
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Mobile-Marketing-bro.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Isi Form</h2>
								<p>Isi form permintaan dengan memencet tombol di bawah ini</p>
							</div>
							<a href="" class="button fit-content">Telusuri</a>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Content-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2 id="tahap-1">Masukkan data yang dibutuhkan</h2>
								<p>Butuh melakukan permintaan publikasi di kanal media organisasi?</p>
							</div>
						</div>
					 </div>
					<div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Mail-sent-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Pantau progress permintaan</h2>
								<p>Ingin meminta persetujuan dan tanda tangan dari organisasi?</p>
							</div>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Customer-Survey-amico.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Selesai</h2>
								<p>Membutuhkan survei untuk kepentingan penelitian dan pengembangan?</p>
							</div>
						</div>
					 </div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

home/templates/surat.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <meta charset="UTF-8">
    <title>Home</title>
<link rel="stylesheet" href="{% static 'main/css/style-detail.css' %}">
  <script type="application/javascript" src="{% static 'main/js/script.js' %}"></script>
{% endblock meta %}

{% block content %}
	<div class="content-home">
        <div class="filler"></div>
        <div class="home-top">
			<div class="home-top-color-filter">
				<div>
					<h1>Surat Menyurat</h1>
					<p>Lakukan pengajuan tanda tangan untuk kepentingan surat menyurat kamu dengan memencet tombol di bawah ya</p>
                    <a href="{% url 'surat:formsurat' %}" class="button fit-content">Ajukan surat</a>
{#					<a href="" class="button fit-content">Ajukan sertifikat</a>#}

				</div>
				<object class="only-desktop" data="{% static 'main/svg/Mail-sent-pana.svg' %}" type="image/svg+xml"></object>
			</div>
		</div>
        <div class="home-middle">
			<div class="home-middle-top">
				<object data="{% static 'main/svg/Questions-pana.svg' %}" type="image/svg+xml"></object>
				<div class="only-desktop">
					<h2>Simak cara melakukan permintaan surat menyurat di bawah ini!</h2>
					<p>Kalian masih bingung cara menggunakan website SIT? Yuk, Kami ajarin!</p>
				</div>
				<div class="only-mobile">
					<h2>Simak cara melakukan permintaan surat menyurat di bawah ini!</h2>
					<p>Kalian masih bingung cara menggunakan website SIT? Yuk, Kami ajarin!</p>
				</div>
			</div>
			<div>
				<h1 class="home-features">Langkah-langkah</h1>
				<div class="home-middle-bottom">
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Piggy-bank-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Isi Form</h2>
								<p>Isi form permintaan dengan memencet tombol di bawah ini</p>
							</div>
							<a href="" class="button fit-content">Telusuri</a>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Content-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2 id="tahap-1">Masukkan data yang dibutuhkan</h2>
								<p>Butuh melakukan permintaan publikasi di kanal media BEM UI?</p>
							</div>
						</div>
					 </div>
					<div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Mail-sent-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Pantau progress permintaan</h2>
								<p>Ingin meminta persetujuan dan tanda tangan dari BEM UI?</p>
							</div>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Customer-Survey-amico.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Selesai</h2>
								<p>Membutuhkan survei untuk kepentingan penelitian dan pengembangan?</p>
							</div>
						</div>
					 </div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}