feedback/urls.py
from . import views
from django.urls import path

app_name = 'feedback'

urlpatterns = [
    path('form/<str:id>/<str:jenis>', views.formFeedback, name='formfeedback'),
    path('postformfeedback', views.postFormFeedback, name='postformfeedback'),
    path('detail/<str:id>', views.detail, name='detail'),
    path('delete', views.delete, name='delete')

]

home/urls.py
from django.urls import path
from .views import index, keuangan, surat, publikasi

app_name = 'home'

urlpatterns = [
    path('', index, name='home'),
    path('keuangan', keuangan, name='keuangan'),
    path('surat', surat, name='surat'),
    path('publikasi', publikasi, name='publikasi'),
]

reimbursement/urls.py
from django.urls import path
from .views import *

app_name = 'reimbursement'

urlpatterns = [
    path('form', form_reimbursement, name='form_reimbursement'),
    path('postForm', post_form_reimbursement, name='post_form_reimbursement'),
    path('detail/<str:id>', detail, name='detail'),
    path('delete', delete, name='delete')
]

requestmanagementsystem/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('surat/', include(('surat.urls', 'surat'), namespace='surat')),
    path('keuangan/', include(('reimbursement.urls', 'reimbursement'), namespace='reimbursement')),
    path('upload-photo', include('backend.urls')),
    path('publikasi/', include(('publikasi.urls', 'publikasi'), namespace='publikasi')),
    path('dashboard-pengurus/', include(('dashpengurus.urls', 'dashpengurus'), namespace='dashboard_pengurus')),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('feedback/', include(('feedback.urls', 'feedback'), namespace='feedback')),

]

reimbursement/views.py
import json

from django.http import Http404
from django.shortcuts import render, redirect
from backend.CRUD.crud_user import user_read
from backend.CRUD.crud_keuangan import *
from backend.misc import firebase_init, getPhoto

# Initialize Firebase Database
fauth = firebase_init

# ---------------------
# Form Request Reimbursement
# --------------------
def form_reimbursement(request):
    try:
        if (request.session['uid']):
            if (fauth.get_account_info(request.session['uid'])):
                return render(request, 'form_reimbursement.html')
            else:
                return redirect("/user/logout")
    except:
        return redirect("/user/login")

def post_form_reimbursement(request):
    judul = request.POST.get("judul")
    nama_kegiatan = request.POST.get("nama_kegiatan")
    deskripsi_kegiatan = request.POST.get("deskripsi_kegiatan")
    nama_bank = request.POST.get("nama_bank")
    nomor_rekening = request.POST.get("nomor_rekening")
    atas_nama_rekening = request.POST.get("atas_nama_rekening")
    jumlah_dana = request.POST.get("jumlah_dana")
    photos = request.POST.get("uploadFiles")
    photos = json.loads(photos)
    print(photos)

    # Upload data to firebase
    if photos[0]["successful"]:
        photos_meta = []
        for i in photos[0]["successful"]:
            photos_meta.append(i["meta"]["id_firebase"])
        message = reimbursement_create(request, judul, nama_kegiatan, deskripsi_kegiatan, jumlah_dana, nomor_rekening, atas_nama_rekening, nama_bank, photos_meta)
        if message != "terjadi error":
            return redirect("/keuangan/detail/" + message)
        else:
            message = "Gagal Upload"
            return redirect('reimbursement:form_reimbursement')
    else:
        message = "Gagal Upload"
        return redirect('reimbursement:form_reimbursement')

# ---------------------
# Detail Reimbursement
# --------------------
def detail(request, id):
    try:
        if (request.session['uid']):
            user_session = fauth.get_account_info(request.session['uid'])
            if (user_session):
                data_detail = reimbursement_read(id)
                user = user_read(user_session['users'][0]['localId'])
                if (data_detail != []):
                    if (user["id"] == data_detail["id_pemohon"] or "keuangan" in user["admin"]):
                        # Get Dokumen Files
                        if ("keuangan" in user["admin"]):
                            admin = "true"
                        else:
                            admin = "false"
                    data_photo = []
                    # Get Photos Bukti Pembayaran
                    for photo in data_detail['bukti_pembayaran']:
                        url = getPhoto.getPhoto(photo)
                        data_photo.append(url)
                    # Get Bukti Transfer
                    try:
                        url = getPhoto.getPhoto(data_detail['bukti_transfer'][0])
                        transfer = url
                    except:
                        transfer = ''
                    print(data_detail)
                    print(data_photo)
                    return render(request, 'reimbursement_details.html', {
                        'data': data_detail,
                        'id': id,
                        'admin':admin,
                        'photos': data_photo,
                        'transfer': transfer,
                        'user': user
                    })
                else:
                    return redirect("/user/logout")
        else:
            return redirect("/user/login")
    except:
        return redirect("/user/login")

def delete(request):
    try:
        if (request.session['uid']):
            user_session = fauth.get_account_info(request.session['uid'])
            if (user_session):
                user = user_read(user_session['users'][0]['localId'])
                if ("keuangan" in user["admin"]):
                    print('masuk')
                    id_request = request.POST.get("id_request")
                    print(id_request)
                    data = reimbursement_delete(id_request)
                    print(data)
                    return redirect('home:publikasi')
            else:
                return redirect('user:logout')
    except:
        return redirect('user:signin')

reimbursement/templates/form_reimbursement.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Form Reimbursement</title>
    <link rel="stylesheet" href="{% static 'reimbursement/css/style.css' %}"/>
    <link href="https://releases.transloadit.com/uppy/v2.9.4/uppy.min.css" rel="stylesheet"/>
{% endblock meta %}

{% block content %}
    <div class="content-root">
        <div class="form-root">
            <h1 id="judul-form">Form Pengajuan Reimbursement</h1>
            <section>
                <form action="postForm" method="post" id="form">
                    {% csrf_token %}
                    <label for="judul" >Judul</label>
                    <input type="text" id="judul" name="judul" placeholder="Judul Permintaan..."> <br/>

                    <label for="kegiatan" >Nama Kegiatan</label>
                    <input type="text" id="kegiatan" name="nama_kegiatan" placeholder="Nama Kegiatan..."><br/>

                    <label for="deskripsi">Deskripsi Singkat Kegiatan</label>
                    <input type="text" id="deskripsi" name="deskripsi_kegiatan" placeholder="Deksripsi Singkat..."><br/>

                    <label for="rekening">Nomor Rekening</label>
                    <input type="number" id="rekening" name="nomor_rekening" placeholder="Nomor Rekening..."><br/>

                    <label for="atas-nama">Atas Nama Rekening</label>
                    <input type="text" id="atas-nama" name="atas_nama_rekening" placeholder="Atas Nama Rekening..."><br/>

                    <label for="bank">Nama Bank Rekening</label>
                    <input type="text" id="bank" name="bank" placeholder="Nama bank rekening anda..."><br/>

                    <label for="nominal">Nominal Reimburse</label>
                    <input type="number" id="nominal" name="jumlah_dana" placeholder="Nominal Uang Reimburse..."><br/>

                    <label class="control-label">Upload Bukti Pembayaran</label>
                    <div class="uppy" id="drag-drop-area"></div>

                    <div class="filler"></div>

                    <input name="uploadFiles" type="hidden">

                </form>

                <button type="button" class="button" id="submitbutton">Submit</button>

                <div class="filler"></div>

                <!-- Script upload ke Bukti Pembayaran-->
                <script src="https://releases.transloadit.com/uppy/v2.9.4/uppy.min.js"></script>
                <script>
                    var uppy = new Uppy.Core()

                    uppy.on('file-added', (file) => {
                        uppy.setFileMeta(file.id, {
                            id_firebase: "KEUANGAN_REIMBURSE/BUKTI_PEMBAYARAN/" + uuidv4(),
                        })
                    })
                    uppy.use(Uppy.XHRUpload, {
                        endpoint: '{% url "upload_photo" %}',
                        headers: {'X-CSRFToken':"{{csrf_token}}"},
                        formData: true,
                        fieldName: 'file'
                    })
                    uppy.use(Uppy.Dashboard, {
                        inline: true,
                        target: '#drag-drop-area',
                        proudlyDisplayPoweredByUppy:false,
                        showProgressDetails:true,
                        doneButtonHandler: null,
                        hideUploadButton: true,
                    })
                    uppy.on('complete', (result) => {
                        console.log('Upload complete! We’ve uploaded these files:', result.successful)
                    })
                    uppy.use(Uppy.Form, {
                        target: "#form",
                        resultName: 'uploadFiles',
                        getMetaFromForm: false,
                        addResultToForm: true,
                        submitOnSuccess: true,
                        triggerUploadOnSubmit: false,
                    })
                </script>
                <script type="application/javascript" src="{% static 'reimbursement/js/scripts.js' %}"></script>
                <script src="https://releases.transloadit.com/uppy/v2.9.4/uppy.min.js"></script>
            </section>
        </div>
    <object class="object only-desktop" data="{% static 'reimbursement/svg/Topup-credit-bro.svg' %}" type="image/svg+xml"></object>
    </div>
{% endblock content %}

reimbursement/templates/reimbursement_details.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Detail Reimbursement-{{data.judul}}</title>
    <link rel="stylesheet" href="{% static 'reimbursement/css/style-details.css' %}">
{% endblock meta %}

{% block content %}
    <div class="content-root">
		<a href="{% url 'home:keuangan' %}" id="button-kembali">&lt Kembali</a>
		{% if admin == "true" %}
            <div class="button-del" onclick="document.getElementById('modal_del').style.display='block'">
            <svg enable-background="new 0 0 32 32" height="1em" id="Layer_1" version="1.1" viewBox="0 0 32 32" width="1em" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="trash"><path clip-rule="evenodd" d="M29.98,6.819c-0.096-1.57-1.387-2.816-2.98-2.816h-3v-1V3.001   c0-1.657-1.344-3-3-3H11c-1.657,0-3,1.343-3,3v0.001v1H5c-1.595,0-2.885,1.246-2.981,2.816H2v1.183v1c0,1.104,0.896,2,2,2l0,0v17   c0,2.209,1.791,4,4,4h16c2.209,0,4-1.791,4-4v-17l0,0c1.104,0,2-0.896,2-2v-1V6.819H29.98z M10,3.002c0-0.553,0.447-1,1-1h10   c0.553,0,1,0.447,1,1v1H10V3.002z M26,28.002c0,1.102-0.898,2-2,2H8c-1.103,0-2-0.898-2-2v-17h20V28.002z M28,8.001v1H4v-1V7.002   c0-0.553,0.447-1,1-1h22c0.553,0,1,0.447,1,1V8.001z" fill="#f00000" fill-rule="evenodd"/><path clip-rule="evenodd" d="M9,28.006h2c0.553,0,1-0.447,1-1v-13c0-0.553-0.447-1-1-1H9   c-0.553,0-1,0.447-1,1v13C8,27.559,8.447,28.006,9,28.006z M9,14.005h2v13H9V14.005z" fill="#f00000" fill-rule="evenodd"/><path clip-rule="evenodd" d="M15,28.006h2c0.553,0,1-0.447,1-1v-13c0-0.553-0.447-1-1-1h-2   c-0.553,0-1,0.447-1,1v13C14,27.559,14.447,28.006,15,28.006z M15,14.005h2v13h-2V14.005z" fill="#f00000" fill-rule="evenodd"/><path clip-rule="evenodd" d="M21,28.006h2c0.553,0,1-0.447,1-1v-13c0-0.553-0.447-1-1-1h-2   c-0.553,0-1,0.447-1,1v13C20,27.559,20.447,28.006,21,28.006z M21,14.005h2v13h-2V14.005z" fill="#f00000" fill-rule="evenodd"/></g></svg>
            <span style="color: red">Delete</span>
            </div>
        {% endif %}

		<div id="modal_del" class="modal">
			<span onclick="document.getElementById('modal_del').style.display='none'" class="close" title="Close Modal">×</span>
			<form class="modal-content-del" action="../delete" method="post">
				{% csrf_token %}
				<input name="id_request" type="hidden" value={{ id }}>
				<div class="container">
				<h1>Delete Permohonan</h1>
				<p>Apakah anda yakin untuk menghapus permohonan?</p>
  
				<div class="clearfix">
				  <button type="button" onclick="document.getElementById('modal_del').style.display='none'" class="modal-button-del cancelbtn">Cancel</button>
				  <button type="submit" onclick="document.getElementById('modal_del').style.display='none'" class="modal-button-del deletebtn">Delete</button>
				</div>
			  </div>
			</form>
		  </div>
		
		<div class="details-judul">
			<h2>{{data.judul}}</h2> <br>
			<h2>({{data.id_permintaan}})</h2>
		</div>

		<div class="details-info detail-only-desktop">
			<h1>Data Pesanan</h1>
			<br>
			<div class="row">
				<div class="column">
					<h3>Pemohon</h3>
					<p>{{data.id_pemohon}}</p>
					<h3>Nama Kegiatan</h3>
					<p>{{data.nama_kegiatan}}</p>
					<h3>Deskripsi Kegiatan</h3>
					<p>{{data.deskripsi_kegiatan}}</p>
				</div>
				<div class="column">
					<h3>Nominal Reimbursement</h3>
					<p class="currency">{{data.jumlah_dana}}</p>
					<h3>Data Rekening</h3>
					<p>{{data.atas_nama_rekening}}<br>{{data.nomor_rekening}}<br>{{data.bank}}</p>
				</div>
			</div>
		</div>
		<div class="details-info only-mobile">
			<h1>Data Pesanan</h1>
			<br>
			<h3>Pemohon</h3>
			<p></p>
			<h3>Nama Kegiatan</h3>
			<p>{{data.nama_kegiatan}}</p>
			<h3>Deskripsi Kegiatan</h3>
			<p>{{data.deskripsi_kegiatan}}</p>
			<h3>Nominal Reimbursement</h3>
			<p class="currency">{{data.jumlah_dana}}</p>
			<h3>Data Rekening</h3>
			<p>{{data.atas_nama_rekening}}</p>
			<p>{{data.nomor_rekening}}</p>
			<h3>Voucher</h3>
		</div>

		<div class="bukti-pembayaran">
			<h3>Bukti Pembayaran</h3>
			{% for photo in photos %}
			<img class="bukti-image" src='{{ photo }}'/>
			<div class="modal">
				<span class="close">&times;</span>
				<img class="modal-content" src="{{photo}}">
			</div>
			{% endfor %}
		</div>

		{% if transfer != "" %}
		<div class="transfer">
			<h3>Bukti Transfer</h3>
			<img class="bukti-image" src='{{ transfer }}'/>
			<div class="modal">
				<span class="close">&times;</span>
				<img class="modal-content" src="{{transfer}}">
			</div>
		</div>
		{% endif %}

        <div class="button-outer">
        {% if "keuangan" in user.admin and data.id_feedback == ''%}
            <a href="{% url 'feedback:formfeedback' id=id jenis='keuangan' %}" class="button">Masukkan Feedback</a>
        {% elif data.id_feedback != '' %}
            <a href="{% url 'feedback:detail' id=data.id_feedback %}" class="button">Lihat Feedback</a>
        {% endif %}
		</div>

	
	</div>
    <script type="application/javascript" src="{% static 'reimbursement/js/scripts-details.js' %}"></script>
	{% endblock content %}