dashpengurus/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('<str:category>/', views.dashboard_pengurus, name='dashboard_pengurus'),
]

home/urls.py
from django.urls import path
from .views import index, keuangan, surat, publikasi

app_name = 'home'

urlpatterns = [
    path('', index, name='home'),
    path('keuangan', keuangan, name='keuangan'),
    path('surat', surat, name='surat'),
    path('publikasi', publikasi, name='publikasi'),
]

requestmanagementsystem/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('surat/', include(('surat.urls', 'surat'), namespace='surat')),
    path('keuangan/', include(('reimbursement.urls', 'reimbursement'), namespace='reimbursement')),
    path('upload-photo', include('backend.urls')),
    path('publikasi/', include(('publikasi.urls', 'publikasi'), namespace='publikasi')),
    path('dashboard-pengurus/', include(('dashpengurus.urls', 'dashpengurus'), namespace='dashboard_pengurus')),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('feedback/', include(('feedback.urls', 'feedback'), namespace='feedback')),

]

user/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    path('login', login, name='login'),
    path('postlogin', postLogin, name='postlogin'),
    path('signup', signUp, name='signup'),
    path('postsignup', postSignUp, name='postsignup'),
    path('dashboard', dashboard, name='dashboard'),
    path('logout', logout, name='logout')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'base/css/style.css' %}">
  <link rel="shortcut icon" href="{% static 'base/img/rms-logo-no-bg.png' %}"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="application/javascript" src="{% static 'base/js/script.js' %}"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
	<header {% if '/' == request.path %}class="header-transparent"{% else %}class="header-white"{% endif %}>
        <a href="{% url 'home:home' %}" class="logo"><img src="{% static 'base/img/rms-logo-no-bg.png' %}" style="width:3.5rem; height:3.5rem;"></a>
        <input type="checkbox" class="nav-toggle" id="nav-toggle">

        <nav>
            <ul>
                <li><a href="{% url 'home:keuangan' %}">Keuangan</a></li>
                <li><a href="{% url 'home:publikasi' %}">Publikasi</a></li>
                <li><a href="{% url 'home:surat' %}">Surat</a></li>
{#                <li><a href="">Survei</a></li>#}
                {% if request.session.admin %}
                    <li><a href="">Give Permission</a></li>
                    <li><a href="">SignUp</a></li>
                {% endif %}
                {% if not request.session.uid %}
                <li class="nav-only-desktop">
                    <a href="" class="button fit-content" style="height: fit-content; margin: 0; padding: 0.6em 1em;">Masuk</a>
                </li>
                <div class="nav-dropdown-buttons nav-only-mobile">
                    <a href="" class="nav-only-mobile button btn-dashboard">
                        Masuk
                    </a>
                </div>
                {% endif %}
                {% if request.session.uid %}
                <li class="nav-only-desktop">
                    <a href="{% url 'dashboard:dashboard' 'home'%}" class="button fit-content" style="height: fit-content; margin: 0; padding: 0.6em 1em;">Dashboard</a>
                </li>
                    <li class="nav-only-desktop">
                    <a href="{% url 'dashboard_pengurus:dashboard_pengurus' 'home'%}" class="button fit-content" style="height: fit-content; margin: 0; padding: 0.6em 1em;">Dashboard Pengurus</a>
                </li>
                <div class="nav-dropdown-buttons nav-only-mobile">
                    <a href="" class="nav-only-mobile button btn-dashboard">
                        Dashboard
                    </a>
                </div>
                {% endif %}
            </ul>
        </nav>

        <label for="nav-toggle" class="nav-toggle-label" id="nav-toggle-label"><span></span></label>

    </header>

    <div class="content-container">
        {% block content %}
        {% endblock content %}
	</div>

    <footer>
        <div class="footer-upper">
            <div class="footer1">
                <a href=""><img src="{% static 'base/img/rms-logo-white-no-bg.png' %}" style="width:7rem; height:6rem;"></a>
            </div>

            <div class="footer3 nav-only-mobile">
                <p>
                    <svg width="24" height="24" viewBox="0 0 24 24">
                        <use href="{% static 'base/svg/base-sprite-sheet.svg' %}#copyright-logo"></use>
                    </svg>
                    @ 2022 - Aki Runcoko - RPL B
                </p>
            </div>
        </div>

        <div class="footer-middle nav-only-desktop">
            <div class="footer1-middle footer-mid">
                <a href=""><strong>Keuangan</strong></a>
                <a href=""><p>Reimbursement</p></a>
                <br>
                <a href=""><strong>Publikasi</strong></a>
                <a href=""><p>Publikasi</p></a>
            </div>
            <div class="footer2-middle footer-mid">
                <a href=""><strong>Surat Menyurat</strong></a>
                <a href=""><p>LPJ, SPK, MoU</p></a>
{#                <a href=""><p>Aki Runcoko</p></a>#}
{#                <a href=""><p>sertifikat</p></a>#}
            </div>
        </div>

        <div class="footer-bottom nav-only-desktop">
            <div>
                <svg width="24" height="24" viewBox="0 0 24 24">
                    <use href="{% static 'base/svg/base-sprite-sheet.svg' %}#copyright-logo"></use>
                </svg>
                <p>2022 - Aki Runcoko - RPL B</p>
            </div>
        </div>
        </div>
    </footer>
</body>

</html>