dashboard/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('<str:category>/', views.dashboard, name='dashboard'),
]

home/urls.py
from django.urls import path
from .views import index, keuangan, surat, publikasi

app_name = 'home'

urlpatterns = [
    path('', index, name='home'),
    path('keuangan', keuangan, name='keuangan'),
    path('surat', surat, name='surat'),
    path('publikasi', publikasi, name='publikasi'),
]

requestmanagementsystem/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('surat/', include(('surat.urls', 'surat'), namespace='surat')),
    path('keuangan/', include(('reimbursement.urls', 'reimbursement'), namespace='reimbursement')),
    path('upload-photo', include('backend.urls')),
    path('publikasi/', include(('publikasi.urls', 'publikasi'), namespace='publikasi')),
    path('dashboard-pengurus/', include(('dashpengurus.urls', 'dashpengurus'), namespace='dashboard_pengurus')),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('feedback/', include(('feedback.urls', 'feedback'), namespace='feedback')),

]

user/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    path('login', login, name='login'),
    path('postlogin', postLogin, name='postlogin'),
    path('signup', signUp, name='signup'),
    path('postsignup', postSignUp, name='postsignup'),
    path('dashboard', dashboard, name='dashboard'),
    path('logout', logout, name='logout')
]

dashboard/views.py
from backend.misc import firebase_init
fauth = firebase_init

from django.http import Http404
from django.shortcuts import render, redirect

from backend.CRUD.crud_publikasi import publikasi_read_requests
from backend.CRUD.crud_surat import surat_read_requests
from backend.CRUD.crud_keuangan import reimbursement_read_requests


from backend.CRUD.crud_user import user_read

def dashboard(request, category):
	try:
		user_session = fauth.get_account_info(request.session['uid'])
		if user_session:
			user = user_read(user_session['users'][0]['localId'])
			print(1)
			print(user['id'])
			print(1)
			data = []
			tahapan = []
			judul = "Home Dashboard"
			if user["admin"]:
				if category == 'publikasi' and 'publikasi' in user['admin']:
					data = publikasi_read_requests(user['id'])
					judul = "Publikasi"
				elif category == "surat" and 'surat' in user['admin']:
					data = surat_read_requests(user['id'])
					judul = "Surat Menyurat"
				elif category == "keuangan" and 'keuangan' in user['admin']:
					data = reimbursement_read_requests(user['id'])
					judul = "Keuangan"
				hostname = request.build_absolute_uri("/")
				print(request.get_full_path)
				#
				# def extract_time(json):
				# 	try:
				# 		return json['waktu_pengajuan']
				# 	except KeyError:
				# 		return 0

				# data.sort(key=extract_time, reverse=False)

				return render(request, 'dashboard.html', {
					'datas': data,
					'user': user,
					'judul': judul,
					'hostname': hostname,
					'category': category,
					'tahapan': tahapan,
				})
			else:
				raise Http404
		else:
			redirect("/user/logout")
	except:
		return redirect("/user/login")

dashboard/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Dashboard</title>
<link rel="stylesheet" href="{% static 'dashpengurus/css/dashboard.css' %}">
{% endblock meta %}

{% block content %}
	<div class="content dashboard-content">
		<div class="dashboard-nav">
			<a class="dashboard-home" href="{% url 'dashboard:dashboard' 'home' %}"><h1>Dashboard</h1></a>
			<div class="dashboard-nav-akun">
				<h4>{{user.email}}</h4>
				<p>{{user.nama}}</p>
				<br>
                <a class="button-sec logout" href="{% url 'user:logout' %}" style="color: #0b2e13">Logout</a>
			</div>
			<hr>
			<div class="dashboard-nav-list">
            {% if 'keuangan' in user.admin %}
				<div class="dashboard-nav-list-judul">
					<svg enable-background="new 0 0 48 48" id="Layer_1" version="1.1" viewBox="0 0 48 48" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path clip-rule="evenodd" d="M47,40L47,40c0,2.762-2.238,5-5,5l0,0H6l0,0c-2.762,0-5-2.238-5-5V11  c0-2.209,1.791-4,4-4l0,0h20.171l8.099-2.934c0.513-0.187,1.081,0.078,1.268,0.589L35.391,7H39c2.209,0,4,1.791,4,4v2l0,0  c2.209,0,4,1.791,4,4V40z M5,9L5,9c-1.104,0-2,0.896-2,2s0.896,2,2,2h3.445l0,0h0.189c0.013-0.005,0.021-0.016,0.034-0.021L19.65,9  H5z M34.078,9.181l-1.062-2.924l-0.001,0v0L30.964,7h0.003l-5.514,2h-0.01l-11.039,4h21.062L34.078,9.181z M41,11  c0-1.104-0.896-2-2-2h-2.883l1.454,4H41l0,0V11z M43,15H5l0,0c-0.732,0-1.41-0.211-2-0.555V40c0,1.657,1.344,3,3,3h36  c1.657,0,3-1.343,3-3v-7h-4c-2.209,0-4-1.791-4-4s1.791-4,4-4h4v-8C45,15.896,44.104,15,43,15z M45,31v-4h-4c-1.104,0-2,0.896-2,2  s0.896,2,2,2H45z M41,28h2v2h-2V28z" fill-rule="evenodd"/></svg>
					<h3>Keuangan</h3>
				</div>
				<div class="dashboard-nav-list-item">
					<br>
					<a href="{% url 'dashboard:dashboard' 'keuangan' %}" class="nav-button"><p {% if 'keuangan' in request.get_full_path %}id="category-focus"{% endif %}> Dana</p></a>
				</div>
				<hr>
            {% endif %}
            {% if 'surat' in user.admin %}
				<div class="dashboard-nav-list-judul">
					<svg data-name="Livello 1" id="Livello_1" viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg"><title/><path d="M116.73,31.83a3,3,0,0,0-4.2-.61L64.14,67.34a1,1,0,0,1-1.2,0L15.5,31.06a3,3,0,1,0-3.64,4.77L49.16,64.36,12.27,92.16A3,3,0,1,0,15.88,97L54.11,68.14l5.18,4a7,7,0,0,0,8.43.06l5.44-4.06L111.84,97a3,3,0,1,0,3.59-4.81L78.17,64.35,116.12,36A3,3,0,0,0,116.73,31.83Z"/><path d="M113,19H15A15,15,0,0,0,0,34V94a15,15,0,0,0,15,15h98a15,15,0,0,0,15-15V34A15,15,0,0,0,113,19Zm9,75a9,9,0,0,1-9,9H15a9,9,0,0,1-9-9V34a9,9,0,0,1,9-9h98a9,9,0,0,1,9,9Z"/></svg>
					<h3>Surat Menyurat</h3>
				</div>
				<div class="dashboard-nav-list-item">
					<br>
					<a href="{% url 'dashboard:dashboard' 'surat' %}" class="nav-button"><p {% if 'surat' in request.get_full_path %}id="category-focus"{% endif %} >Surat Menyurat</p></a>
				</div>
				<hr>
            {% endif %}
            {% if 'publikasi' in user.admin %}
				<div class="dashboard-nav-list-judul">
					<svg data-name="Livello 1" id="Livello_1" viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg"><title/><path d="M116.73,31.83a3,3,0,0,0-4.2-.61L64.14,67.34a1,1,0,0,1-1.2,0L15.5,31.06a3,3,0,1,0-3.64,4.77L49.16,64.36,12.27,92.16A3,3,0,1,0,15.88,97L54.11,68.14l5.18,4a7,7,0,0,0,8.43.06l5.44-4.06L111.84,97a3,3,0,1,0,3.59-4.81L78.17,64.35,116.12,36A3,3,0,0,0,116.73,31.83Z"/><path d="M113,19H15A15,15,0,0,0,0,34V94a15,15,0,0,0,15,15h98a15,15,0,0,0,15-15V34A15,15,0,0,0,113,19Zm9,75a9,9,0,0,1-9,9H15a9,9,0,0,1-9-9V34a9,9,0,0,1,9-9h98a9,9,0,0,1,9,9Z"/></svg>
					<h3>Publikasi</h3>
				</div>
				<div class="dashboard-nav-list-item">
					<br>
					<a href="{% url 'dashboard:dashboard' 'publikasi' %}" class="nav-button"><p {% if 'publikasi' in request.get_full_path %}id="category-focus"{% endif %} >Publikasi</p></a>
				</div>
				<hr>
            {% endif %}
			</div>
		</div>

		<div class="dashboard-body">
			<div class="dashboard-content">
				<div class="dashboard-content-card">
                    <h1>{{ judul }} Pengurus</h1>
                    {% if category == "home" %}
                        <ul class="cards">
                            {% if 'keuangan' in user.admin %}
                            <li>
                                <a href="{% url 'dashboard:dashboard' 'keuangan' %}" class="card">
                                  <img src="{% static 'user/photos/Finance_leaders-pana.png' %}" class="card__image" alt="" />
                                  <div class="card__overlay">
                                    <div class="card__header">
                                        <svg class="card__thumb" enable-background="new 0 0 48 48" id="Layer_1" version="1.1" viewBox="0 0 48 48" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path clip-rule="evenodd" d="M47,40L47,40c0,2.762-2.238,5-5,5l0,0H6l0,0c-2.762,0-5-2.238-5-5V11  c0-2.209,1.791-4,4-4l0,0h20.171l8.099-2.934c0.513-0.187,1.081,0.078,1.268,0.589L35.391,7H39c2.209,0,4,1.791,4,4v2l0,0  c2.209,0,4,1.791,4,4V40z M5,9L5,9c-1.104,0-2,0.896-2,2s0.896,2,2,2h3.445l0,0h0.189c0.013-0.005,0.021-0.016,0.034-0.021L19.65,9  H5z M34.078,9.181l-1.062-2.924l-0.001,0v0L30.964,7h0.003l-5.514,2h-0.01l-11.039,4h21.062L34.078,9.181z M41,11  c0-1.104-0.896-2-2-2h-2.883l1.454,4H41l0,0V11z M43,15H5l0,0c-0.732,0-1.41-0.211-2-0.555V40c0,1.657,1.344,3,3,3h36  c1.657,0,3-1.343,3-3v-7h-4c-2.209,0-4-1.791-4-4s1.791-4,4-4h4v-8C45,15.896,44.104,15,43,15z M45,31v-4h-4c-1.104,0-2,0.896-2,2  s0.896,2,2,2H45z M41,28h2v2h-2V28z" fill-rule="evenodd"/></svg>
                                        <div class="card__header-text">
                                            <h3 class="card__title">DANA</h3>
                                        </div>
                                    </div>
                                    <p class="card__description">Masuk ke dashboard Dana</p>
                                  </div>
                                </a>
                              </li>
                            {% endif %}
                            {% if 'surat' in user.admin %}
                            <li>
                                <a href="{% url 'dashboard:dashboard' 'surat' %}" class="card">
                                  <img src="{% static 'user/photos/Fill_out-bro.png' %}" class="card__image" alt="" />
                                  <div class="card__overlay">
                                    <div class="card__header">
					                    <svg class="card__thumb" data-name="Livello 1" id="Livello_1" viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg"><title/><path d="M116.73,31.83a3,3,0,0,0-4.2-.61L64.14,67.34a1,1,0,0,1-1.2,0L15.5,31.06a3,3,0,1,0-3.64,4.77L49.16,64.36,12.27,92.16A3,3,0,1,0,15.88,97L54.11,68.14l5.18,4a7,7,0,0,0,8.43.06l5.44-4.06L111.84,97a3,3,0,1,0,3.59-4.81L78.17,64.35,116.12,36A3,3,0,0,0,116.73,31.83Z"/><path d="M113,19H15A15,15,0,0,0,0,34V94a15,15,0,0,0,15,15h98a15,15,0,0,0,15-15V34A15,15,0,0,0,113,19Zm9,75a9,9,0,0,1-9,9H15a9,9,0,0,1-9-9V34a9,9,0,0,1,9-9h98a9,9,0,0,1,9,9Z"/></svg>
                                        <div class="card__header-text">
                                        <h3 class="card__title">Surat Menyurat</h3>
                                      </div>
                                    </div>
                                    <p class="card__description">Masuk ke dashboard Surat Menyurat</p>
                                  </div>
                                </a>
                              </li>
                            {% endif %}
                            {% if 'publikasi' in user.admin %}
                                <li>
                                    <a href="{% url 'dashboard:dashboard' 'publikasi' %}" class="card">
                                      <img src="{% static 'user/photos/Fill_out-bro.png' %}" class="card__image" alt="" />
                                      <div class="card__overlay">
                                        <div class="card__header">
                                            <svg class="card__thumb" data-name="Livello 1" id="Livello_1" viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg"><title/><path d="M116.73,31.83a3,3,0,0,0-4.2-.61L64.14,67.34a1,1,0,0,1-1.2,0L15.5,31.06a3,3,0,1,0-3.64,4.77L49.16,64.36,12.27,92.16A3,3,0,1,0,15.88,97L54.11,68.14l5.18,4a7,7,0,0,0,8.43.06l5.44-4.06L111.84,97a3,3,0,1,0,3.59-4.81L78.17,64.35,116.12,36A3,3,0,0,0,116.73,31.83Z"/><path d="M113,19H15A15,15,0,0,0,0,34V94a15,15,0,0,0,15,15h98a15,15,0,0,0,15-15V34A15,15,0,0,0,113,19Zm9,75a9,9,0,0,1-9,9H15a9,9,0,0,1-9-9V34a9,9,0,0,1,9-9h98a9,9,0,0,1,9,9Z"/></svg>
                                            <div class="card__header-text">
                                            <h3 class="card__title">Publikasi</h3>
                                          </div>
                                        </div>
                                        <p class="card__description">Masuk ke dashboard Publikasi</p>
                                      </div>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    {% else %}
                    <h2>List Permintaan</h2>
                    <div class="dashboard-background">
                        {% for data in datas %}
                            <a onclick="openInNewTab('{{ hostname }}{{ category }}/detail/{{ data.id_permintaan }}');" class="request" {% if data.isInsidental %} style="background: #8b0000" {% endif %}>
                                <div class="request-div">
                                    <div class="request-div-header">
                                        <h2>{{ data.judul }}</h2>
                                        <div class="request-time-post-desktop">
                                            {% if data.waktu_pengajuan_str %}
                                                {{ data.waktu_pengajuan_str }}
                                            {% else %}
                                                {{ data.waktu_pengajuan }}
                                            {% endif %}
                                            <br>
                                        </div>
                                    </div>
                                    <div class="request-div-body">
                                        <div>
                                            <p class="request-div-body-status"></p>
                                            <p>Dipesan Oleh:</p>
                                            <p><strong>{{ data.id_pemohon }}</strong></p>
                                        </div>
                                        <div class="request-time-post-mobile">
                                            {% if data.waktu_pengajuan_str %}
                                                {{ data.waktu_pengajuan_str }}
                                            {% else %}
                                                {{ data.waktu_pengajuan }}
                                            {% endif %}
                                            <br>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
			</div>
		</div>
	</div>

	<script type="text/javascript">
		function openInNewTab(url) {
			window.open(url, '_blank').focus();
		}
	</script>
{% endblock content %}